language: ruby
rvm:
  - 3.0.3
services:
  - postgresql
install:
  bundle install --jobs=3 --retry=3
script:
  - bundle exec rails db:setup
before_script:
  - psql -c 'create database desafio_socinal_test;' -U postgres